import type { CategoryCard } from '../types'

export const CATEGORIES: CategoryCard[] = [
  {
    id: 'earphone',
    label: 'Enjoy With',
    title: '',
    bigText: 'EARPHONE',
    bg: '#1a1a2e',
    textLight: true,
    colSpan: 1,
    emoji: '🎧',
    buttonVariant: 'primary',
  },
  {
    id: 'smartwatch',
    label: 'New',
    title: 'Wear Gear',
    bigText: 'EARPHONE',
    bg: '#F4B800',
    textLight: true,
    colSpan: 1,
    emoji: '⌚',
    buttonVariant: 'outline',
  },
  {
    id: 'laptop',
    label: 'Trend',
    title: 'Devices',
    bigText: 'LAPTOP',
    bg: '#E84040',
    textLight: true,
    colSpan: 2,
    emoji: '💻',
    buttonVariant: 'outline',
  },
  {
    id: 'console',
    label: 'Best',
    title: 'Gaming',
    bigText: 'CONSOLE',
    bg: '#f0f0f0',
    textLight: false,
    colSpan: 2,
    emoji: '🎮',
    buttonVariant: 'deal',
  },
  {
    id: 'oculus',
    label: 'Play',
    title: 'Game',
    bigText: 'OCULUS',
    bg: '#4CAF50',
    textLight: true,
    colSpan: 1,
    emoji: '🥽',
    buttonVariant: 'outline',
  },
  {
    id: 'speaker',
    label: 'New',
    title: 'Amazon',
    bigText: 'SPEAKER',
    bg: '#2196F3',
    textLight: true,
    colSpan: 1,
    emoji: '🔊',
    buttonVariant: 'outline',
  },
]
