import type { Deal } from '../types'

export const LIGHTNING_DEALS: Deal[] = [
  {
    id: '1',
    discount: -27,
    featured: true,
    brand: 'Hcetigol',
    name: 'Cosmic Byte GS410 Headset with Mic',
    rating: 4,
    reviews: 6,
    price: 152.99,
    originalPrice: 209.99,
    vendor: 'Abril Copeland',
    sold: 9,
    total: 24,
    emoji: '🎧',
  },
  {
    id: '2',
    discount: -35,
    brand: 'MEO',
    name: 'DriftingWood Solid Wood Coffee Table',
    rating: 4,
    reviews: 4,
    price: 58.90,
    originalPrice: 89.99,
    vendor: 'Scarlett Rivas',
    sold: 27,
    total: 50,
    emoji: '🪑',
  },
  {
    id: '3',
    discount: -17,
    brand: 'Elppa',
    name: 'Elppa iPed Pro (2018) Wifi + 3G',
    rating: 4,
    reviews: 4,
    price: 499.90,
    originalPrice: 599.90,
    vendor: 'Gia Marquez',
    sold: 44,
    total: 101,
    emoji: '📱',
  },
  {
    id: '4',
    discount: -26,
    brand: 'Elgoog',
    name: 'Geoglo Pexel 3a XL 2018 Plus',
    rating: 4,
    reviews: 4,
    price: 890.90,
    originalPrice: 1209.99,
    vendor: 'Gia Marquez',
    sold: 41,
    total: 96,
    emoji: '📲',
  },
  {
    id: '5',
    discount: -33,
    brand: 'ESORMIRP',
    name: 'PRIMROSE Eclipse Fabric 3 Seater Sofa',
    rating: 3,
    reviews: 3,
    price: 199.90,
    originalPrice: 299.99,
    vendor: 'Gia Marquez',
    sold: 100,
    total: 169,
    emoji: '🛋️',
  },
]
