import type { PopularProduct } from '../types'

export const POPULAR_PRODUCTS: PopularProduct[] = [
  {
    id: 'pp-1',
    name: 'Tactical Backpack Pro Series',
    price: 45.99,
    originalPrice: 49.99,
    discount: 7,
    category: 'Sports',
    emoji: '🎒',
  },
  {
    id: 'pp-2',
    name: 'Wireless Noise-Cancel Headset',
    price: 89.99,
    originalPrice: 119.99,
    category: 'Electronics',
    emoji: '🎧',
  },
  {
    id: 'pp-3',
    name: 'Smart Watch Series 5 Ultra',
    price: 125.00,
    originalPrice: 130.00,
    discount: 4,
    category: 'Tech',
    emoji: '⌚',
  },
  {
    id: 'pp-4',
    name: 'Portable Bluetooth Speaker',
    price: 59.99,
    originalPrice: 79.99,
    category: 'Audio',
    emoji: '🔊',
  },
  {
    id: 'pp-5',
    name: 'Gaming Mechanical Keyboard',
    price: 79.00,
    originalPrice: 99.00,
    discount: 10,
    category: 'Gaming',
    emoji: '⌨️',
  },
  {
    id: 'pp-6',
    name: 'USB-C Fast Charge Hub',
    price: 34.99,
    category: 'Accessories',
    emoji: '🔌',
  },
  {
    id: 'pp-7',
    name: 'Action Camera Waterproof 4K',
    price: 149.99,
    originalPrice: 189.99,
    discount: 5,
    category: 'Cameras',
    emoji: '📷',
  },
  {
    id: 'pp-8',
    name: 'Smart LED Desk Lamp',
    price: 29.99,
    originalPrice: 39.99,
    category: 'Home',
    emoji: '💡',
  },
]
