/** Liste des villes/communes de Côte d'Ivoire — partagée entre le panier et le carnet
 *  d'adresses du profil pour garantir des valeurs identiques (nécessaire à la déduplication
 *  automatique des adresses). */
export const VILLES_CI = {
  'Abidjan — Communes': [
    'Abidjan – Abobo',
    'Abidjan – Adjamé',
    'Abidjan – Attécoubé',
    'Abidjan – Cocody',
    'Abidjan – Koumassi',
    'Abidjan – Marcory',
    'Abidjan – Plateau',
    'Abidjan – Port-Bouët',
    'Abidjan – Treichville',
    'Abidjan – Yopougon',
    'Abidjan – Bingerville',
    'Abidjan – Anyama',
    'Abidjan – Songon',
    'Abidjan – Grand-Bassam',
    'Abidjan – Jacqueville',
  ],
  'Autres villes': [
    'Yamoussoukro',
    'Bouaké',
    'Daloa',
    'Korhogo',
    'San-Pédro',
    'Man',
    'Gagnoa',
    'Abengourou',
    'Divo',
    'Soubré',
    'Dimbokro',
    'Agboville',
    'Bondoukou',
    'Ferkessédougou',
    'Odienné',
    'Séguéla',
    'Touba',
    'Bouna',
    'Bangolo',
    'Issia',
    'Oumé',
    'Daoukro',
    'Bongouanou',
    'Adzopé',
    'Tiassalé',
    'Guiglo',
    'Duékoué',
    'Tabou',
  ],
}
